### ISSUE TITLE
Error using env files

### ISSUE THREAD

**Issue by phelipe** [jellydn/hurl.nvim#142]
### Details
Following the docs, the plugin should work with the vars.env file and get the variable values, but I always get an error. Below are pieces of information to try to reproduce the problem. Am I doing something wrong or is this a bug?

plugin config

```lua
return {
  'jellydn/hurl.nvim',
  dependencies = {
    'MunifTanjim/nui.nvim',
    'nvim-treesitter/nvim-treesitter',
  },
  ft = 'hurl',
  opts = {
    -- Show debugging info
    debug = false,
    -- Show notification on run
    show_notification = false,
    -- Show response in popup or split
    mode = 'split',
    -- Default formatter
    formatters = {
      json = { 'jq' }, -- Make sure you have install jq in your system, e.g: brew install jq
      html = {
        'prettier', -- Make sure you have install prettier in your system, e.g: npm install -g prettier
        '--parser',
        'html',
      },
    },
  },
  keys = {
    -- Run API request
    { '<leader>rr', '<cmd>HurlRunnerAt<CR>', desc = '[R]un Api [R]equest' },
  },
}

```

plugin version
```
hurl.nvim 
  url    https://github.com/jellydn/hurl.nvim
  branch main
  commit 2531f2a
  readme README.md
  help   |hurl.nvim.txt|
  ft     hurl
  keys   <leader>rr
````

hurl file
```hurl
POST {{API_HOST}}/v1/login
```
vars.env file
```env
API_HOST = "http://localhost:3001"

```
output of HurlRunnerAt
```bash
  || error: Undefined variable
   --> /home/phelipe/.cache/nvim/6456-1710854193.hurl|1| 8
   ||    |
   ||  1 | POST {{API_HOST}}/v1/login
   ||    |        ^^^^^^^^ you must set the variable API_HOST

```

<details open>
<summary>Checklist</summary>

- [X] Modify `lua/hurl/main.lua` ✓ https://github.com/jellydn/hurl.nvim/commit/4fad53879aad1f7b760298bf37316a0a6646fb94 [Edit](https://github.com/jellydn/hurl.nvim/edit/sweep/error_using_env_files/lua/hurl/main.lua)
- [X] Running GitHub Actions for `lua/hurl/main.lua` ✗  [Edit](https://github.com/jellydn/hurl.nvim/edit/sweep/error_using_env_files/lua/hurl/main.lua)
</details>

**Comment by jellydn** [comment]
You have an invalid value on your .env file.

Please change to

``sh
API_HOST=http://localhost:3001
```
