### ISSUE TITLE
Feature: add captured value to global environments

### ISSUE THREAD

**Issue by huantrinh1802** [jellydn/hurl.nvim#149]
### Context (current usage):

- First step is an auth step to obtain 1hour token session.
- I either:
  - Run the whole file and pass the captured token to the next requests
  - Manually add the token to the global environment variables

### Desired behaviour:

- Run auth step with the `[Captures]` section
- The captured token should be added in the global environment variables
- Able to run other requests

<details open>
<summary>Checklist</summary>

- [X] Modify `lua/hurl/main.lua` ✓ https://github.com/jellydn/hurl.nvim/commit/718562de8fa92670410f15dbca0949491b742d81 [Edit](https://github.com/jellydn/hurl.nvim/edit/sweep/feature_add_captured_value_to_global_env/lua/hurl/main.lua)
- [X] Running GitHub Actions for `lua/hurl/main.lua` ✗  [Edit](https://github.com/jellydn/hurl.nvim/edit/sweep/feature_add_captured_value_to_global_env/lua/hurl/main.lua)
</details>

**Comment by jellydn** [comment]
Hi @huantrinh1802 Thank you for raising this issue but I don't think that's a good fit for this plugin. Will close as it's NOT planned.

**Comment by jandrewthompson** [comment]
> Hi @huantrinh1802 Thank you for raising this issue but I don't think that's a good fit for this plugin. Will close as it's NOT planned.

Would also find this feature extremely useful.

**Comment by phenax** [comment]
+1. Manually setting variables that are obtained dynamically is a chore. This plugin seems perfect minus this one odd thing.

**Comment by jellydn** [comment]
As I said, I don't have a plan to implement this. PRs are welcome. Probably you need to flag for on/off this feature.

**Comment by jellydn** [comment]
It's done by #207 Please give a try and let me know if any issue. Thanks.
