### ISSUE TITLE
popup result window appear at strange position in nvim 0.10

### ISSUE THREAD

**Issue by wenjinnn** [jellydn/hurl.nvim#159]
### Details
Hi there, first of all thanks for build this amazing plugin.
This issue is only shows with nvim 0.10, which I upgraded recently.
Maybe this is relate on nui.nvim?
The screenshot after running `HurlRunnerAt`:
![image](https://github.com/jellydn/hurl.nvim/assets/30885216/653282f1-26fc-475b-9acb-9d024a84c3d1)

**Comment by jellydn** [comment]
Hi @wenjinnn I tried to reproduce but I can't reproduce the issue. I guess something with nui.nvim library and somehow they've fixed the issue.
