### ISSUE TITLE
Nui popup is not working well

### ISSUE THREAD

**Issue by realtica** [jellydn/hurl.nvim#170]
### Details: Nvim 0.10.0
Hello, 

For some info like Global variables the popup works well but for results, only works in split mode.. help me please.

![image](https://github.com/jellydn/hurl.nvim/assets/852446/69248ba4-037b-48f3-8081-a57b4a7eaf5d)

**Comment by jellydn** [comment]
Thanks @realtica I will take a look on this issue sometime this week.

**Comment by jellydn** [comment]
Hi @realtica Could you help me to reproduce this issue? I tried but it's fine on my end. 

-  What is your config? 
-  Could you record video or write the reproduce steps?

**Comment by jellydn** [comment]
Fixed with latest commit.
