### ISSUE TITLE
Sweep: Artifact in the response window

### ISSUE THREAD

**Issue by Barmaley0** [jellydn/hurl.nvim#173]
### Details
Windows 10
neovim 0.9.5
Hello. What additional equipment may be associated with in the “^M” response window. And in the implementation it seems to be there and everything should work, but for some reason there is no language coloring?
config hurl
![image](https://github.com/jellydn/hurl.nvim/assets/133758633/c4912795-4053-417d-8a51-44b6b7b46a88)

config formatting
![image](https://github.com/jellydn/hurl.nvim/assets/133758633/0e1bbb0b-314c-42df-824a-e1f656656b13)

![image](https://github.com/jellydn/hurl.nvim/assets/133758633/a47929ac-39cf-475f-9936-ce12b4d23ab7)

**Comment by Barmaley0** [comment]
I also noticed that if I continue to close the tab with the answer “q”, it always returns inconsistently until I re-login completely. Re-open the file and tabotate everything again.
![image](https://github.com/jellydn/hurl.nvim/assets/133758633/0a4dfa19-cf1a-490b-9102-cac26886d7f7)

**Comment by jellydn** [comment]
I will close this one as I can't reproduce this issue. 

P/S: I'm using Macbook.

**Comment by Krztk** [comment]
Stdout returned form the formatter has `\r\n` line endings. That's default line ending in windows OS. 

Something like this in the format function should fix the issue for windows users. @Barmaley0 @jellydn 
```
for i, line in ipairs(stdout) do
  stdout[i] = line:gsub('\r', '')
end

return stdout
```
