### ISSUE TITLE
Customize "close" mapping

### ISSUE THREAD

**Issue by yngwi** [jellydn/hurl.nvim#184]
Hi, thank you for the plugin, the integration into Neovim makes Hurl much more convenient. I am looking for a way to customize the mapping to close the popup/split response view. By default, it is `q`. Is there a way to make it `<c-q>`?

**Comment by jellydn** [comment]
Hi @yngwi Could you send PR about this? I can give a hint for you. 

For example, you could refer to https://github.com/CopilotC-Nvim/CopilotChat.nvim how to define the mapping and implement it. In our case, I think it should have something like this

```lua
  -- default mappings
  mappings = {
    close = 'q',
    next_panel = "<C-n>",
    prev_panel = "<C-p>"
  }
```
