### ISSUE TITLE
Bug: formatter errors are not handled correctly

### ISSUE THREAD

**Issue by mariemachtmiau** [jellydn/hurl.nvim#215]
### Details

When running HurlRunner the split opens but nothing happens. Debugged it and found it was getting stuck here
https://github.com/jellydn/hurl.nvim/blob/18d3e68149f5014f501b3e2d5b03332c42e02b93/lua/hurl/utils.lua#L120

It tries to format html, even when setting `formatters = {},` in setup. Also doesn't seem to handle prettier not existing right, it just gets stuck (even with debug the last log is the one from L119.
It works when I change the html formatter to `{ "cat" }`, but that's permanent, I'd like it to dynamically format if the executable exists and just ignore it if not (basically exactly what the code should already be doing).

When running the commands manually `vim.v.shell_error ~= 0` is true, so it should normally work. 

```
NVIM v0.10.2
```

**Comment by jellydn** [comment]
Could you share your config? @mariemachtmiau Also run `:checkhealth hurl` and share the output with me.

**Comment by mariemachtmiau** [comment]
My config is basically just
```lua
    require("hurl").setup({
      fixture_vars = {},
      formatters = {
        -- NOTE: for now use cat as error handling is broken when formatter is not found
        html = { "cat" },
      },
    })
```
(also had debug and notifications turned on before when debugging). I use Nixvim to configure my Neovim and used the tag v2.0.0 to build the plugin.

Checkhealth:
```
hurl: require("hurl.health").check()

hurl.nvim health check ~
- OK jq found
- ERROR prettier not found
- OK treesitter[hurl]: installed
- OK hurl version > 4.3.0 found
- OK hurl.nvim: All good!

```

**Comment by mariemachtmiau** [comment]
Logs:
```
hurl: running current file
hurl: running request
hurl: looking for { "vars.env" } in [...]
hurl: looking for { "vars.env" } in /tmp/vars.env
hurl: running command: hurl /tmp/test.hurl --verbose
hurl: request finished
formatting body with html
```

Everything works completely fine with HurlVerbose and HurlVeryVerbose btw, also json (cuz it skips formatting there).

**Comment by jellydn** [comment]
Thanks @mariemachtmiau It should be okay now.

**Comment by mariemachtmiau** [comment]
Thanks for the quick fix @jellydn  :)
