### ISSUE TITLE
[Feature] jq intergration for result

### ISSUE THREAD

**Issue by cenk1cenk2** [jellydn/hurl.nvim#22]
Dear @jellydn,

Thank you for this beautiful plugin I wanted to use hurl with neovim for a while now, and I am lucky that I have stumbled on your video about it.

Is there any way possible or do you find it in the scope of the project to be able to `jq` into the result of the request. It would be a good novelty to have something like as follows:

- After the request finishes, popup or split opens up.
- If you press some key bind it will bring up a `vim.ui.input` box where you can enter your `jq` query.
- After you are done you may list it under the result or just swap the page with the `jq` result that is changeable by a key bind to the original request.

I can give it a go at this if you find this behavior in the scope of the project, but I am not sure when due to my current work load.

**Comment by jellydn** [comment]
I guess your main idea is how to filter the data with large JSON object.

> I can give it a go at this if you find this behavior in the scope of the project

Sorry, I don't think we should bring this hurl.nvim. That would be a `json viewer` plugin scope :).

**Comment by cenk1cenk2** [comment]
Great thanks for the reply. I suppose yeah it may be something out of the scope of the project.
