### ISSUE TITLE
Missing Payload in Response with Neovim 0.9.4

### ISSUE THREAD

**Issue by htquangg** [jellydn/hurl.nvim#36]
I try to get payload in response, but nothing does.

https://github.com/jellydn/hurl.nvim/assets/41544778/fa389849-949a-4ef8-ac64-3e044217ae91

**Comment by htquangg** [comment]
Hi @jellydn, I already did but the same...
<img width="432" alt="Screenshot 2023-12-01 at 8 23 29 PM" src="https://github.com/jellydn/hurl.nvim/assets/41544778/8fc616a8-c903-4939-b38a-f717ec2aee54">

**Comment by jellydn** [comment]
What is your Neovim version? @htquangg I am trying to understand and reproduce the issue as your video.

**Comment by htquangg** [comment]
> What is your Neovim version? @htquangg I am trying to understand and reproduce the issue as your video.

0.9.4 @jellydn

**Comment by htquangg** [comment]
I double check and found main issue in line: https://github.com/jellydn/hurl.nvim/blob/main/lua/hurl/split.lua#L53

**Comment by jellydn** [comment]
Fixed by https://github.com/jellydn/hurl.nvim/commit/c3a4311567c7dee1ea36e305c2a7bbddb030a9b6
