### ISSUE TITLE
[Feature] Add action to filter the response

### ISSUE THREAD

**Issue by skoch13** [jellydn/hurl.nvim#58]
This might not be the right case for Hurl here because it has filters for test runners. My case is to filter the response, similar to how Insomnia does it with the same JSONPath.

**Comment by jellydn** [comment]
Hi @skoch13 I think this would be add-on on top of the buffer. There is a similar request here https://github.com/jellydn/hurl.nvim/issues/22.

**Comment by skoch13** [comment]
@jellydn okay!
