### ISSUE TITLE
The response in the split window has no syntax

### ISSUE THREAD

**Issue by xfyuan** [jellydn/hurl.nvim#59]
I have installed the neovim treesitter `hurl` and the highlight in hurl file is good now:

<img width="885" alt="image" src="https://github.com/jellydn/hurl.nvim/assets/5710838/ac13f405-65ff-4d3b-a476-367e0c2dd2d2">

But the response in the split window has none syntax:

<img width="842" alt="image" src="https://github.com/jellydn/hurl.nvim/assets/5710838/542eb199-89f6-4dfe-9307-ddfabb02e47c">

**The demo gif in the repo readme seems have syntax on both cases. Do I miss some configs?**

PS.

I found the split window use the `hurl-nvim` filetype, it seems neovim don't know how to syntax on it. If I change it to `hurl` filetype, then it works.) But after search the plugin source, the split buffer filetype can't support customize now: https://github.com/jellydn/hurl.nvim/blob/main/lua/hurl/split.lua#L10

**Comment by skoch13** [comment]
Here is the similar topic I asked within discussions: https://github.com/jellydn/hurl.nvim/discussions/55

**Comment by Aietes** [comment]
Maybe this helps, this is how you add syntax highlight via treesitter to all filetypes with `.hurl`, including `.hurl-nvim`

```lua
return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = function(_, opts)
      -- other config
      local parser_configs = require("nvim-treesitter.parsers").get_parser_configs()
      parser_configs.hurl = {
        install_info = {
          url = "~/git/github.com/kjuulh/tree-sitter-hurl",
          files = { "src/parser.c" },
          branch = "main",
          generate_requires_npm = false,
          requires_generate_from_grammar = false,
        },
        filetype = "*.hurl*",
      }

      vim.filetype.add({
        pattern = {
          [".*%.hurl.*"] = "hurl",
        },
      })
    end,
  },
}

```

**Comment by xfyuan** [comment]
> Maybe this helps, this is how you add syntax highlight via treesitter to all files with `.hurl`, including `.hurl-nvim` by using a pattern for matching the filetype:
> 
> ```lua
> return {
>   {
>     "nvim-treesitter/nvim-treesitter",
>     opts = function(_, opts)
>       -- other config
>       local parser_configs = require("nvim-treesitter.parsers").get_parser_configs()
>       parser_configs.hurl = {
>         install_info = {
>           url = "~/git/github.com/kjuulh/tree-sitter-hurl",
>           files = { "src/parser.c" },
>           branch = "main",
>           generate_requires_npm = false,
>           requires_generate_from_grammar = false,
>         },
>         filetype = "*.hurl*",
>       }
> 
>       vim.filetype.add({
>         pattern = {
>           [".*%.hurl.*"] = "hurl",
>         },
>       })
>     end,
>   },
> }
> ```

Because the neovim treesitter already has the `hurl` so I used it directly, and put the `vim.filetype.add` into the `config` part, like below:

```vim
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    event = "BufReadPost",
    opts = {
      sync_install = false,
      ensure_installed = {
        "bash",
        "cmake",
        "css",
        "html",
        "help",
        "http",
        "hurl",
        "markdown",
    ......
    config = function(_, opts)
      require("nvim-treesitter.configs").setup(opts)
      vim.filetype.add({
        pattern = {
          [".*%.hurl.*"] = "hurl",
        },
      })
    end,
```
But it doesn't work 😢

**Comment by Aietes** [comment]
It looks like there are errors in your config. The way you are trying to access treesitter configs looks wrong to me. Try to put all your options into the config function, i.e. the stuff from `opts = {}`, and remove opts. Please try this and see if it works:

```lua
return {
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    event = "BufReadPost",
    opts = function(_, opts)
      vim.list_extend(opts.ensure_installed, {
        "bash",
        "cmake",
        "css",
        "html",
        "help",
        "http",
        "hurl",
        "markdown",
      })
      local parser_configs = require("nvim-treesitter.parsers").get_parser_configs()
      parser_configs.hurl = {
        install_info = {
          url = "~/git/github.com/kjuulh/tree-sitter-hurl",
          files = { "src/parser.c" },
          branch = "main",
          generate_requires_npm = false,
          requires_generate_from_grammar = false,
        },
        filetype = "*.hurl*",
      }

      vim.filetype.add({
        pattern = {
          [".*%.hurl.*"] = "hurl",
        },
      })
    end,
  },
}
```

**Comment by Aietes** [comment]
@ruckerzerg Your config looks right, however, there can be many things that potentially prevent syntax highlighting from working. One thing that comes to mind: The tree-sittter-hurl used here requires node to work. I'm not sure what your setup is, but you could try to use another parser, that is not depended on node. It's easy to try out, just replace the url line with this:

```lua
url = "~/git/github.com/pfeiferj/tree-sitter-hurl",
```

Make sure you always restart nvim to when testing if it works. 😉

**Comment by Aietes** [comment]
Ok, I misunderstood your first comment, I thought it wasn't working at all. I just see the execution in split view doesn't have a name. Therefore treesitter cannot know which parser to attach. It would be helpful if the plugin names the buffer, that way it should work. This requires a change in the plugin itself though.

**Comment by Aietes** [comment]
Just tested it, that's it. On the neovim nightly build the solution above will work, but not on latest 0.9.x
