### ISSUE TITLE
Split view not showing

### ISSUE THREAD

**Issue by Aietes** [jellydn/hurl.nvim#60]
For some reason the split view is not showing, instead the entire window gets taken over by a blank buffer. It looks like the split result flashes for a millisecond, but then there is just an empty buffer, even replacing the hurl file. Sometimes the split window works, but mostly not. I couldn't pin down what makes it work or break. The popup works fine, and works every single time, but I'd prefer split mode. Any idea what could cause the issue, and how I can fix it?

I'm on LazyVim, and don't use Edgy.

**Comment by jellydn** [comment]
Thanks @Aietes let me try to reproduce this issue.

**Comment by Aietes** [comment]
Thank you! Great plugin btw, I was looking for something like this for a while! Keep up the good work!

**Comment by Aietes** [comment]
Update: Split view doesn't work on neovim stable/0.9.5, on the nightly build it works fine and reliable.

**Comment by jellydn** [comment]
It should work now @Aietes Let me know if any issue with split view.
