### ISSUE TITLE
The response is not formatted (json/html)

### ISSUE THREAD

**Issue by Viroide** [jellydn/hurl.nvim#98]
### ❗  After some debugging, I found that the body is truncated, probably the payload is too big. ❗

![image](https://github.com/jellydn/hurl.nvim/assets/713362/df20471e-2091-4517-b1e9-5f3a4efcf9f8)

I have both installed `jq` and `prettier` any clue?

debug info
```
[INFO  Wed Mar  6 13:52:12 2024] ...utils.lua:19: hurl: request finished
[INFO  Wed Mar  6 13:52:12 2024] ...utils.lua:19: Detected content type: application/json; charset=utf-8
[INFO  Wed Mar  6 13:52:12 2024] ...utils.lua:19: formatting body with json
[ERROR Wed Mar  6 13:52:12 2024] ...utils.lua:30: formatter failed4
```

<details open>
<summary>Checklist</summary>

- [X] Modify `lua/hurl/utils.lua` ✓ https://github.com/jellydn/hurl.nvim/commit/0c558503f490a73b0d7c9cec5b8396ca7e92e9d8 [Edit](https://github.com/jellydn/hurl.nvim/edit/sweep/the_response_is_not_formatted_jsonhtml/lua/hurl/utils.lua#L105-L128)
- [X] Running GitHub Actions for `lua/hurl/utils.lua` ✗  [Edit](https://github.com/jellydn/hurl.nvim/edit/sweep/the_response_is_not_formatted_jsonhtml/lua/hurl/utils.lua#L105-L128)
- [X] Modify `lua/hurl/main.lua` ! No changes made  [Edit](https://github.com/jellydn/hurl.nvim/edit/sweep/the_response_is_not_formatted_jsonhtml/lua/hurl/main.lua#L216-L246)
- [X] Running GitHub Actions for `lua/hurl/main.lua` ✗  [Edit](https://github.com/jellydn/hurl.nvim/edit/sweep/the_response_is_not_formatted_jsonhtml/lua/hurl/main.lua#L216-L246)
</details>

**Comment by skoch13** [comment]
I have the very same issue, moreover ever the 'headers table' is getting truncated too.

**Comment by jellydn** [comment]
Thank you @Viroide for your report. It's failed on the format process: `formatter failed4`. I will try to reproduce the issue sometime this week. PR's welcome if you could reproduce the issue on your own.
